# service-repos/auth_api/helm/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: auth-app-service
  labels:
    app: auth-app
spec:
  type: ClusterIP
  selector:
    app: auth-app
  ports:
    - port: 3000
      targetPort: 3000