# # auth_app/.github/workflows/deploy.yml

# name: Deploy

# on:
#   push:
#     branches:
#       - dev
#       - main

# jobs:
#   build-and-push:
#     name: Build and Push Docker Image
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v2

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2

#       - name: Log in to Amazon ECR
#         id: login-ecr
#         uses: aws-actions/amazon-ecr-login@v3
#         with:
#           region: us-east-1

#       - name: Build Docker Image
#         run: |
#           docker build -t auth_app -f Dockerfile.dev .
#           docker tag auth_app:latest ${{ steps.login-ecr.outputs.registry }}/auth_app:latest

#       - name: Push to ECR
#         run: |
#           docker push ${{ steps.login-ecr.outputs.registry }}/auth_app:latest

#       - name: Set Image Tag Output
#         id: image_tag
#         run: echo "::set-output name=tag::latest"

#     outputs:
#       image_tag: ${{ steps.image_tag.outputs.tag }}

#   terraform:
#     name: Terraform Apply
#     needs: build-and-push
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v2
#         with:
#           terraform_version: "1.3.0"

#       - name: Terraform Init
#         run: terraform init

#       - name: Terraform Apply
#         run: terraform apply -auto-approve -var="image_tag=${{ needs.build-and-push.outputs.image_tag }}" -var="db_password=${{ secrets.DB_PASSWORD }}"
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
